### ISSUE TITLE
Error: Invalid mnemonic

### ISSUE THREAD

**Issue by kkomelin** [suidouble/sui_meta_miner#1]
When used the private key from the site popup "Address And Private Key":

```bash
node mine.js --chain=mainnet --phrase="suiprivkey1........"
/srv/sites/sui/suidouble/sui_meta_miner/node_modules/@scure/bip39/index.js:31
        throw new Error('Invalid mnemonic');
              ^

Error: Invalid mnemonic
    at normalize (/srv/sites/sui/suidouble/sui_meta_miner/node_modules/@scure/bip39/index.js:31:15)
    at mnemonicToSeedSync (/srv/sites/sui/suidouble/sui_meta_miner/node_modules/@scure/bip39/index.js:141:50)
    at mnemonicToSeed (/srv/sites/sui/suidouble/sui_meta_miner/node_modules/@mysten/sui/dist/cjs/cryptography/mnemonics.js:42:46)
    at mnemonicToSeedHex (/srv/sites/sui/suidouble/sui_meta_miner/node_modules/@mysten/sui/dist/cjs/cryptography/mnemonics.js:45:32)
    at Ed25519Keypair.deriveKeypair (/srv/sites/sui/suidouble/sui_meta_miner/node_modules/@mysten/sui/dist/cjs/keypairs/ed25519/keypair.js:131:104)
    at new SuiMaster (/srv/sites/sui/suidouble/sui_meta_miner/node_modules/suidouble/lib/SuiMaster.js:73:52)
    at run (file:///srv/sites/sui/suidouble/sui_meta_miner/mine.js:9:23)
    at file:///srv/sites/sui/suidouble/sui_meta_miner/mine.js:31:1
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)

Node.js v20.16.0
```

I understand that mnemonic and this format are different. Is it possible to accept both formats via cli to make user life simple? Thx

**Comment by jeka-kiselyov** [comment]
Good point, thanks @kkomelin 

Update it  ( [fe576aec95c309642e4094373f07cb0ca0b1ca1d](https://github.com/suidouble/sui_meta_miner/commit/fe576aec95c309642e4094373f07cb0ca0b1ca1d) already in main branch ), now it also accepts "suiprivkey....",

same command:   `node mine.js --chain=mainnet --phrase="suiprivkey...."`

**Comment by kkomelin** [comment]
Thank you @jeka-kiselyov !
