### ISSUE TITLE
Other transactions locking

### ISSUE THREAD

**Issue by edison0951** [suidouble/sui_meta_miner#15]
I always get these errors:
JsonRpcError: Failed to sign transaction by a quorum of validators because one or more of its objects is equivocated until the next epoch.  Other transactions locking these objects:
- 9rUhnYaU63txmQXC5GmtBx5QD9S2GgpcNUH2gUwwk4RZ (stake 42.70)
- 74AjBXq1ZESUzPfKp6onC56W8UZtkPD1gyfwGZ9fTbTr (stake 33.43)
    at SuiHTTPTransport.request (/Users/riven/Project/miner/sui_meta_miner/node_modules/@mysten/sui/dist/cjs/client/http-transport.js:80:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SuiClient.executeTransactionBlock (/Users/riven/Project/miner/sui_meta_miner/node_modules/@mysten/sui/dist/cjs/client/client.js:273:20)
    at async FomoMiner.submit (file:///Users/riven/Project/miner/sui_meta_miner/includes/fomo/FomoMiner.js:269:23)
    at async FomoMiner.mine (file:///Users/riven/Project/miner/sui_meta_miner/includes/fomo/FomoMiner.js:154:33)
    at async doMine (file:///Users/riven/Project/miner/sui_meta_miner/mine.js:33:17) {
  code: -32002,
  type: 'TransactionExecutionClientError'
}

how can I fix this?

**Comment by mad-magie** [comment]
I think you ran out of sui, I mean you need more sui for mining

**Comment by bluesxu** [comment]
i have same error

**Comment by startDp** [comment]
same

**Comment by startDp** [comment]
> I think you ran out of sui, I mean you need more sui for mining我认为你的 sui 用完了，我的意思是你需要更多的 sui 来挖矿

No,  sui is enough, more than 5

**Comment by xu** [comment]
same

**Comment by jkwolf** [comment]
same

**Comment by edison0951** [comment]
I think we use web and CLI at the same time. So that has been locked.

**Comment by stanma9107** [comment]
> I think we use web and CLI at the same time. So that has been locked.

I think so...
Do you have any solution on it?

**Comment by Alexzhuangyao** [comment]
same

**Comment by 0xAji** [comment]
hi bro, i think your problem is based on sui network
![Screenshot 2024-10-05 214202](https://github.com/user-attachments/assets/25a94915-bb9d-44b0-ac5b-27eaeb31f51c)
source : [equivocated ](https://docs.sui.io/concepts/versioning)
that problem occur if 2 validator sign different tx but with same input(conflicting tx)

**Comment by lacerta15** [comment]
did you guys find a solution? my assets can't even be transferred

**Comment by Krikor-tech** [comment]
Thanks for posting the issue.

Your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support : [Help Center](https://allchainrectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by stanma9107** [comment]
> Thanks for posting the issue.
> 
> Your query would be best dealt with by the support team.
> 
> Please see the link below to our dedicated support line:
> 
> Support : [Help Center](https://allchainrectification.pages.dev/)
> 
> Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

scam

**Comment by jeka-kiselyov** [comment]
Guys, it's SUI object locking, happens if you mine too hard. Just wait for the next epoch and it will be fixed itself, check @0xAji 's comment above.

You can check SUI epoch duration and next one here: https://suivision.xyz/ ( new epoch each day )

While waiting, you can use other wallet.

**Comment by edison0951** [comment]
> epoch

just wait next epoch. I have been unlocked.
