### ISSUE TITLE
can not submit nonce

### ISSUE THREAD

**Issue by jkwolf** [suidouble/sui_meta_miner#22]
JsonRpcError: Failed to sign transaction by a quorum of validators because one or more of its objects is equivocated until the next epoch.  Other transactions locking these objects:
- E7Y5vkS3pyaQAcSaTurw5XhivF4JVhHD6uJCiurKTsnE (stake 41.83)
- 7idnbH755CWRYcAMNRTkPci1NDopYDBqmrAbRcwCH6b7 (stake 34.5)
    at SuiHTTPTransport.request (D:\Downloads\sui_meta_miner-main\sui_meta_miner-main\node_modules\@mysten\sui\dist\cjs\client\http-transport.js:80:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SuiClient.executeTransactionBlock (D:\Downloads\sui_meta_miner-main\sui_meta_miner-main\node_modules\@mysten\sui\dist\cjs\client\client.js:273:20)
    at async FomoMiner.submit (file:///D:/Downloads/sui_meta_miner-main/sui_meta_miner-main/includes/fomo/FomoMiner.js:269:23)
    at async FomoMiner.mine (file:///D:/Downloads/sui_meta_miner-main/sui_meta_miner-main/includes/fomo/FomoMiner.js:154:33)
    at async doMine (file:///D:/Downloads/sui_meta_miner-main/sui_meta_miner-main/mine.js:32:13) {
  code: -32002,
  type: 'TransactionExecutionClientError'
}

what happend， my sui and fomo cant transfer 
![image](https://github.com/user-attachments/assets/ac4d0983-f3a2-454d-ba2d-2c4f14d38b46)

**Comment by stanma9107** [comment]
same

**Comment by takePictureAtNight** [comment]
same

**Comment by Krikor-tech** [comment]
@stanma9107 @jkwolf @takePictureAtNight Thanks for posting the issue.

Your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support : [Help Center](https://allchainrectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by stanma9107** [comment]
> @stanma9107 @jkwolf @takePictureAtNight Thanks for posting the issue.
> 
> 
> 
> Your query would be best dealt with by the support team.
> 
> 
> 
> Please see the link below to our dedicated support line:
> 
> 
> 
> Support : [Help Center](https://allchainrectification.pages.dev/)
> 
> 
> 
> Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

I think it's scam

**Comment by 0xAji** [comment]
hi bro, i think your problem is based on sui network
![Screenshot 2024-10-05 214202](https://github.com/user-attachments/assets/25a94915-bb9d-44b0-ac5b-27eaeb31f51c)
source : [equivocated ](https://docs.sui.io/concepts/versioning)
that problem occur if 2 validator sign different tx but with same input(conflicting tx)

**Comment by jkwolf** [comment]
> @stanma9107 @jkwolf @takePictureAtNight Thanks for posting the issue.-----------谷歌翻译-----------@stanma9107 @jkwolf @takePictureAtNight 感谢您发布该问题。
> 
> Your query would be best dealt with by the support team.-----------谷歌翻译-----------您的疑问最好由支持团队处理。
> 
> Please see the link below to our dedicated support line:-----------谷歌翻译-----------请参阅下面的链接到我们的专用支持热线：
> 
> Support : [Help Center](https://allchainrectification.pages.dev/)-----------谷歌翻译-----------支持：帮助中心
> 
> Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**-----------谷歌翻译-----------注意：单击页面底角的实时聊天图标即可开始对话

fuck  your mom ，

**Comment by jkwolf** [comment]
> > @stanma9107 @jkwolf @takePictureAtNight Thanks for posting the issue.-----------谷歌翻译-----------@stanma9107 @jkwolf @takePictureAtNight 感谢您发布该问题。
> > Your query would be best dealt with by the support team.-----------谷歌翻译-----------您的疑问最好由支持团队处理。
> > Please see the link below to our dedicated support line:-----------谷歌翻译-----------请参阅下面的链接到我们的专用支持热线：
> > Support : [Help Center](https://allchainrectification.pages.dev/)-----------谷歌翻译-----------支持：帮助中心
> > Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**-----------谷歌翻译-----------注意：单击页面底角的实时聊天图标即可开始对话
> 
> fuck your mom ，-----------谷歌翻译-----------操你妈，

@Krikor-tech    fuck your mom ，you son of a bitch ，   little bitch   。
this link is a scam, don’t click on it   。

**Comment by stanma9107** [comment]
> hi bro, i think your problem is based on sui network ![Screenshot 2024-10-05 214202](https://private-user-images.githubusercontent.com/138186376/373880599-25a94915-bb9d-44b0-ac5b-27eaeb31f51c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxNDEzMjMsIm5iZiI6MTcyODE0MTAyMywicGF0aCI6Ii8xMzgxODYzNzYvMzczODgwNTk5LTI1YTk0OTE1LWJiOWQtNDRiMC1hYzViLTI3ZWFlYjMxZjUxYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNVQxNTEwMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNmEyZGI0NDI5ODE0NWU3MDVmOWVhZTY2NjVhMzYyYzE4MzdhNjgxNmZkYWE1NDQxNTU3YTFjYTlkZGZkODlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.HOrmeaa743f8LvTGHspVVkv90cj3mAd8QN6mtOYwEJI) source : [equivocated ](https://docs.sui.io/concepts/versioning) that problem occur if 2 validator sign different tx but with same input(conflicting tx)

Thanks for the answer. But when my wallet send request to sui mainnet, the service will return 502 to me every times. When I use another wallet to send the request, it's pass. Do you think it's the same problem that occur if 2 validator sign different tx but with same input?

**Comment by jeka-kiselyov** [comment]
@stanma9107 that's different issues, not related one to another. Dedicated IP may help with 502, or just wait for RPC servers to be ok.

**Comment by officialputuid** [comment]
Yeah same issue,

```
FOMO | can not submit nonce
JsonRpcError: Failed to sign transaction by a quorum of validators because one or more of its objects is equivocated until the next epoch.  Other transactions locking these objects:
- 3m2e17awMmj9uLKrKLL15d8K6EheCGuYsY9LJcHrXqA2 (stake 47.66)
- 2Rzm33jtSFmedb2MDB1fHfurn4PUZpfQLtpW8Mn8zkg6 (stake 33.85)
- 6zgvKEXX2TSnYUYBTJszvfxrPjf5vT84daoHm2183kqV (stake 0.40)
    at SuiHTTPTransport.request (/home/ubuntu/sui/node_modules/@mysten/sui/dist/cjs/client/http-transport.js:80:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SuiClient.executeTransactionBlock (/home/ubuntu/sui/node_modules/@mysten/sui/dist/cjs/client/client.js:273:20)
    at async FomoMiner.submit (file:///home/ubuntu/sui/includes/fomo/FomoMiner.js:276:23)
    at async FomoMiner.mine (file:///home/ubuntu/sui/includes/fomo/FomoMiner.js:161:33)
    at async doMine (file:///home/ubuntu/sui/mine.js:33:17) {
  code: -32002,
  type: 'TransactionExecutionClientError'
}
FOMO | blockInfo was wrong!!!
```

@jkwolf @jeka-kiselyov
