### ISSUE TITLE
Stopped

### ISSUE THREAD

**Issue by cedok123** [suidouble/sui_meta_miner#8]
Suddenly stopped, I don't know why. There seems to be a problem with the web server, but this script doesn't try again

**Comment by cedok123** [comment]
/project/workspace/sui_meta_miner/node_modules/@mysten/sui/dist/cjs/client/http-transport.js:72
      throw new import_errors.SuiHTTPStatusError(
            ^

SuiHTTPStatusError: Unexpected status code: 429
    at SuiHTTPTransport.request (/project/workspace/sui_meta_miner/node_modules/@mysten/sui/dist/cjs/client/http-transport.js:72:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SuiClient.getOwnedObjects (/project/workspace/sui_meta_miner/node_modules/@mysten/sui/dist/cjs/client/client.js:177:12)
    at async SuiPaginatedResponse.fetch (/project/workspace/sui_meta_miner/node_modules/suidouble/lib/SuiPaginatedResponse.js:67:26)
    at async SuiPackageModule.getOwnedObjects (/project/workspace/sui_meta_miner/node_modules/suidouble/lib/SuiPackageModule.js:292:9)
    at async FomoMiner.getOrCreateMiner (file:///project/workspace/sui_meta_miner/includes/fomo/FomoMiner.js:77:27)
    at async FomoMiner.hasBlockInfoChanged (file:///project/workspace/sui_meta_miner/includes/fomo/FomoMiner.js:111:23) {
  status: 429,
  statusText: 'Too Many Requests'
}

Node.js v20.12.0

**Comment by jeka-kiselyov** [comment]
@cedok123 adjusted it to auto-restart on the error. You can pull new version and try it
